name: CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v5.0.0
      - run: docker compose up -d --build
      - run: |
          for PORT in 8000 8001 8002 8003 8004; do
            MAX_RETRIES=120
            COUNT=0
            
            until curl -sf http://localhost:$PORT/health; do
              COUNT=$((COUNT + 1))
              if [ $COUNT -ge $MAX_RETRIES ]; then
                echo "Service failed to start"
                exit 1
              fi
              sleep 1
            done
          done
          

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app/bookshop
            docker compose up --build -d
